CREATE TYPE public.family_role AS ENUM ('admin','member');
CREATE TABLE public.profiles (id uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE, display_name text NOT NULL DEFAULT '', avatar_url text NOT NULL DEFAULT '', preferences jsonb NOT NULL DEFAULT '{}');
GRANT SELECT, INSERT, UPDATE ON public.profiles TO authenticated; GRANT ALL ON public.profiles TO service_role;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
CREATE POLICY profiles_read ON public.profiles FOR SELECT TO authenticated USING (id=auth.uid());
CREATE POLICY profiles_update ON public.profiles FOR UPDATE TO authenticated USING (id=auth.uid()) WITH CHECK (id=auth.uid());
CREATE TABLE public.user_roles (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), user_id uuid NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE, role public.family_role NOT NULL, UNIQUE(user_id,role));
GRANT SELECT ON public.user_roles TO authenticated; GRANT ALL ON public.user_roles TO service_role;
ALTER TABLE public.user_roles ENABLE ROW LEVEL SECURITY;
CREATE FUNCTION public.has_family_role(_role public.family_role) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid() AND role=_role) $$;
REVOKE ALL ON FUNCTION public.has_family_role(public.family_role) FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.has_family_role(public.family_role) TO authenticated;
CREATE FUNCTION public.is_family_member() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path=public AS $$ SELECT EXISTS(SELECT 1 FROM public.user_roles WHERE user_id=auth.uid()) $$;
REVOKE ALL ON FUNCTION public.is_family_member() FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.is_family_member() TO authenticated;
CREATE POLICY own_roles ON public.user_roles FOR SELECT TO authenticated USING(user_id=auth.uid() OR public.has_family_role('admin'));
CREATE TABLE public.family_invitations (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), email text NOT NULL UNIQUE, role public.family_role NOT NULL DEFAULT 'member', invited_by uuid, created_at timestamptz NOT NULL DEFAULT now(), revoked boolean NOT NULL DEFAULT false);
GRANT SELECT,INSERT,UPDATE,DELETE ON public.family_invitations TO authenticated; GRANT ALL ON public.family_invitations TO service_role;
ALTER TABLE public.family_invitations ENABLE ROW LEVEL SECURITY;
CREATE POLICY admin_invitations ON public.family_invitations FOR ALL TO authenticated USING(public.has_family_role('admin')) WITH CHECK(public.has_family_role('admin'));
CREATE FUNCTION public.create_family_profile() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ BEGIN INSERT INTO public.profiles(id,display_name) VALUES(NEW.id,coalesce(NEW.raw_user_meta_data->>'full_name','')); RETURN NEW; END $$;
CREATE TRIGGER family_profile_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.create_family_profile();
CREATE FUNCTION public.claim_family_invitation() RETURNS boolean LANGUAGE plpgsql SECURITY DEFINER SET search_path=public AS $$ DECLARE member_email text; invited_role public.family_role; BEGIN SELECT lower(email) INTO member_email FROM auth.users WHERE id=auth.uid() AND email_confirmed_at IS NOT NULL; IF member_email IS NULL THEN RETURN false; END IF; SELECT role INTO invited_role FROM public.family_invitations WHERE lower(email)=member_email AND NOT revoked; IF invited_role IS NULL THEN RETURN false; END IF; INSERT INTO public.user_roles(user_id,role) VALUES(auth.uid(),invited_role) ON CONFLICT DO NOTHING; RETURN true; END $$;
REVOKE ALL ON FUNCTION public.claim_family_invitation() FROM PUBLIC; GRANT EXECUTE ON FUNCTION public.claim_family_invitation() TO authenticated;
CREATE TABLE public.family_documents (id text PRIMARY KEY, title text NOT NULL, category text NOT NULL DEFAULT 'plans', source_path text NOT NULL UNIQUE, content_html text NOT NULL, updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.family_documents TO authenticated; GRANT ALL ON public.family_documents TO service_role;
ALTER TABLE public.family_documents ENABLE ROW LEVEL SECURITY;
CREATE POLICY family_documents_read ON public.family_documents FOR SELECT TO authenticated USING(public.is_family_member());
CREATE POLICY family_documents_admin ON public.family_documents FOR ALL TO authenticated USING(public.has_family_role('admin')) WITH CHECK(public.has_family_role('admin'));
CREATE TABLE public.family_tasks (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, done boolean NOT NULL DEFAULT false, created_by uuid NOT NULL DEFAULT auth.uid(), created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.family_tasks TO authenticated; GRANT ALL ON public.family_tasks TO service_role;
ALTER TABLE public.family_tasks ENABLE ROW LEVEL SECURITY;
CREATE POLICY family_tasks_read ON public.family_tasks FOR SELECT TO authenticated USING(public.is_family_member());
CREATE POLICY family_tasks_write ON public.family_tasks FOR ALL TO authenticated USING(public.is_family_member() AND (created_by=auth.uid() OR public.has_family_role('admin'))) WITH CHECK(public.is_family_member() AND (created_by=auth.uid() OR public.has_family_role('admin')));
CREATE TABLE public.family_events (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, event_date date NOT NULL, created_by uuid NOT NULL DEFAULT auth.uid());
GRANT SELECT,INSERT,UPDATE,DELETE ON public.family_events TO authenticated; GRANT ALL ON public.family_events TO service_role;
ALTER TABLE public.family_events ENABLE ROW LEVEL SECURITY;
CREATE POLICY family_events_read ON public.family_events FOR SELECT TO authenticated USING(public.is_family_member());
CREATE POLICY family_events_write ON public.family_events FOR ALL TO authenticated USING(public.has_family_role('admin')) WITH CHECK(public.has_family_role('admin'));
CREATE TABLE public.family_bookmarks (user_id uuid NOT NULL DEFAULT auth.uid(), document_id text NOT NULL REFERENCES public.family_documents(id) ON DELETE CASCADE, PRIMARY KEY(user_id,document_id));
GRANT SELECT,INSERT,DELETE ON public.family_bookmarks TO authenticated; GRANT ALL ON public.family_bookmarks TO service_role;
ALTER TABLE public.family_bookmarks ENABLE ROW LEVEL SECURITY;
CREATE POLICY family_bookmarks_own ON public.family_bookmarks FOR ALL TO authenticated USING(user_id=auth.uid() AND public.is_family_member()) WITH CHECK(user_id=auth.uid() AND public.is_family_member());